SET CACHE_SIZE 16384;         
SET DEFAULT_TABLE_TYPE 0;     
SET CLUSTER '';               
SET DEFAULT_LOCK_TIMEOUT 1000;
SET WRITE_DELAY 500;          
SET IGNORECASE 1;             
;             
CREATE USER IF NOT EXISTS ROOT SALT '84257aa23ef3708c' HASH '57a277a3d0405e5572015c8488e5b00480bc374fa7d0dac832915bc0f288fcc3' ADMIN;         
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B44769F7_57E2_481F_BA1E_4BF749FFE04E START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2EB78FF8_B225_4407_823E_32454252AE64 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A3A42221_1BF3_49B0_B5BA_B4C01F85C064 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A285ADD5_B6F5_4B42_B48D_C4009DAB4630 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F8BF9B01_CE6D_41D3_A3E1_64F4A8AC705B START WITH 3 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C6A016D1_EA01_441A_BA91_0BA95536223B START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_857A83D0_3E71_4894_BDB3_7651B7918AFF START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_09D7C871_E5AF_45A9_A7E3_27404792F68A START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_64B96348_7868_427A_908B_A0D505D75DDE START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D8599C19_42C2_4741_9199_277F1888E07C START WITH 1 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC.CUSTOMER(
    CUSTOMER_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C6A016D1_EA01_441A_BA91_0BA95536223B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C6A016D1_EA01_441A_BA91_0BA95536223B,
    NAME VARCHAR_IGNORECASE(100) DEFAULT NULL,
    PHONE_NO VARCHAR_IGNORECASE(100) DEFAULT NULL,
    EMAIL VARCHAR_IGNORECASE(200) DEFAULT NULL,
    ADDRESS VARCHAR_IGNORECASE(100) DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL
);             
-- 0 = SELECT COUNT(*) FROM PUBLIC.CUSTOMER;  
CREATE CACHED TABLE PUBLIC.PAYMENT(
    PAYMENT_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_857A83D0_3E71_4894_BDB3_7651B7918AFF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_857A83D0_3E71_4894_BDB3_7651B7918AFF,
    CUSTOMER_ID INT DEFAULT NULL,
    PRICE VARCHAR_IGNORECASE(100) DEFAULT NULL,
    PAYED VARCHAR_IGNORECASE(200) DEFAULT NULL,
    PENDING INT DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    BILLINGDATE TIMESTAMP DEFAULT NULL
);           
-- 0 = SELECT COUNT(*) FROM PUBLIC.PAYMENT;   
CREATE CACHED TABLE PUBLIC.PAYMENT_ITEAM(
    PAYMENT_ID INT NOT NULL,
    ITEAM_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B44769F7_57E2_481F_BA1E_4BF749FFE04E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B44769F7_57E2_481F_BA1E_4BF749FFE04E,
    NAME VARCHAR_IGNORECASE(100) DEFAULT NULL,
    UNIT_PRICE INT DEFAULT NULL,
    UNIT_TOTAL INT DEFAULT NULL,
    UNIT_ENTER INT DEFAULT NULL,
    PRICE INT DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    STOCK_ID INT DEFAULT NULL
);     
-- 0 = SELECT COUNT(*) FROM PUBLIC.PAYMENT_ITEAM;             
CREATE CACHED TABLE PUBLIC.STOCKS(
    STOCK_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_09D7C871_E5AF_45A9_A7E3_27404792F68A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_09D7C871_E5AF_45A9_A7E3_27404792F68A,
    NAME VARCHAR_IGNORECASE(100) DEFAULT NULL,
    CATEGORY VARCHAR_IGNORECASE(100) DEFAULT NULL,
    STOCKLEFT INT DEFAULT NULL,
    ORIGINALPRICE INT DEFAULT NULL,
    SUPPLIERS VARCHAR_IGNORECASE(300) DEFAULT NULL,
    SELLINGPRICE INT DEFAULT NULL
);        
-- 0 = SELECT COUNT(*) FROM PUBLIC.STOCKS;    
CREATE CACHED TABLE PUBLIC.PAYMENT_HISTORY(
    PAYMENT_ID INT NOT NULL,
    CUSTOMER_ID INT DEFAULT NULL,
    PRICE VARCHAR_IGNORECASE(100) DEFAULT NULL,
    PAYED VARCHAR_IGNORECASE(200) DEFAULT NULL,
    PENDING INT DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    BILLINGDATE TIMESTAMP DEFAULT NULL
);             
-- 0 = SELECT COUNT(*) FROM PUBLIC.PAYMENT_HISTORY;           
CREATE CACHED TABLE PUBLIC.SUPPLIERS(
    SUPPLIER_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D8599C19_42C2_4741_9199_277F1888E07C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D8599C19_42C2_4741_9199_277F1888E07C,
    NAME VARCHAR_IGNORECASE(100) DEFAULT NULL,
    SUPPLIER_PHONE VARCHAR_IGNORECASE(100) DEFAULT NULL,
    SUPPLIER_ADDRESS VARCHAR_IGNORECASE(100) DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL
);             
-- 0 = SELECT COUNT(*) FROM PUBLIC.SUPPLIERS; 
CREATE CACHED TABLE PUBLIC.SUPPLIER_PAYMENT(
    SUPPLIER_PAYMENT_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2EB78FF8_B225_4407_823E_32454252AE64) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2EB78FF8_B225_4407_823E_32454252AE64,
    SUPPLIER_ID INT DEFAULT NULL,
    TOTAL_AMOUNT VARCHAR_IGNORECASE(100) DEFAULT NULL,
    PAYED_AMOUNT VARCHAR_IGNORECASE(200) DEFAULT NULL,
    PENDING_AMOUNT INT DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    BILLINGDATE TIMESTAMP DEFAULT NULL
);    
-- 0 = SELECT COUNT(*) FROM PUBLIC.SUPPLIER_PAYMENT;          
CREATE CACHED TABLE PUBLIC.SUPPLIER_PAYMENT_HISTORY(
    SUPPLIER_PAYMENT_HISTORY_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A285ADD5_B6F5_4B42_B48D_C4009DAB4630) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A285ADD5_B6F5_4B42_B48D_C4009DAB4630,
    SUPPLIER_PAYMENT_ID INT NOT NULL,
    SUPPLIER_ID INT DEFAULT NULL,
    TOTAL_AMOUNT VARCHAR_IGNORECASE(100) DEFAULT NULL,
    PAYED_AMOUNT VARCHAR_IGNORECASE(200) DEFAULT NULL,
    PENDING_AMOUNT INT DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    BILLINGDATE TIMESTAMP DEFAULT NULL
);              
-- 0 = SELECT COUNT(*) FROM PUBLIC.SUPPLIER_PAYMENT_HISTORY;  
CREATE CACHED TABLE PUBLIC.SUPPLIER_PAYMENT_ITEM(
    SUPPLIER_PAYMENT_ID INT NOT NULL,
    SUPPLIER_ID INT DEFAULT NULL,
    ITEM_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A3A42221_1BF3_49B0_B5BA_B4C01F85C064) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A3A42221_1BF3_49B0_B5BA_B4C01F85C064,
    ITEM_NAME VARCHAR_IGNORECASE(100) DEFAULT NULL,
    UNIT_PRICE INT DEFAULT NULL,
    UNIT_QUANTITY INT DEFAULT NULL,
    TOTAL_PRICE INT DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    STOCK_ID INT DEFAULT NULL
);      
-- 0 = SELECT COUNT(*) FROM PUBLIC.SUPPLIER_PAYMENT_ITEM;     
CREATE CACHED TABLE PUBLIC.USERS(
    USERID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F8BF9B01_CE6D_41D3_A3E1_64F4A8AC705B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F8BF9B01_CE6D_41D3_A3E1_64F4A8AC705B,
    USERNAME VARCHAR_IGNORECASE(100),
    PASSWORD VARCHAR_IGNORECASE(200)
);            
-- 2 = SELECT COUNT(*) FROM PUBLIC.USERS;     
INSERT INTO PUBLIC.USERS(USERID, USERNAME, PASSWORD) VALUES
(1, CAST('admin' AS VARCHAR_IGNORECASE), CAST('admin' AS VARCHAR_IGNORECASE)),
(2, CAST('wadhwa' AS VARCHAR_IGNORECASE), CAST('wadhwa' AS VARCHAR_IGNORECASE));   
CREATE CACHED TABLE PUBLIC.DB_BACKUP_STATUS(
    DB_BACKUP_STATUS_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_64B96348_7868_427A_908B_A0D505D75DDE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_64B96348_7868_427A_908B_A0D505D75DDE,
    FILE_NAME VARCHAR_IGNORECASE(200),
    STATUS VARCHAR_IGNORECASE(50),
    BACKUP_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    WAS_AUTOMATIC BOOLEAN DEFAULT FALSE,
    NEXT_BACKUP_DATE TIMESTAMP
);      
-- 0 = SELECT COUNT(*) FROM PUBLIC.DB_BACKUP_STATUS;          
ALTER TABLE PUBLIC.SUPPLIERS ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(SUPPLIER_ID);     
ALTER TABLE PUBLIC.PAYMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(PAYMENT_ID);        
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(SUPPLIER_PAYMENT_ID);      
ALTER TABLE PUBLIC.STOCKS ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(STOCK_ID);           
ALTER TABLE PUBLIC.PAYMENT_ITEAM ADD CONSTRAINT PUBLIC.CONSTRAINT_59 PRIMARY KEY(ITEAM_ID);   
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT_ITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ITEM_ID);             
ALTER TABLE PUBLIC.DB_BACKUP_STATUS ADD CONSTRAINT PUBLIC.CONSTRAINT_C6 PRIMARY KEY(DB_BACKUP_STATUS_ID);     
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT_HISTORY ADD CONSTRAINT PUBLIC.CONSTRAINT_FF PRIMARY KEY(SUPPLIER_PAYMENT_HISTORY_ID);     
ALTER TABLE PUBLIC.CUSTOMER ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(CUSTOMER_ID);      
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(USERID);              
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT_ITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_783 FOREIGN KEY(SUPPLIER_ID) REFERENCES PUBLIC.SUPPLIERS(SUPPLIER_ID) NOCHECK;      
ALTER TABLE PUBLIC.PAYMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_FB FOREIGN KEY(CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMER(CUSTOMER_ID) NOCHECK;      
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT_HISTORY ADD CONSTRAINT PUBLIC.CONSTRAINT_FFFB FOREIGN KEY(SUPPLIER_ID) REFERENCES PUBLIC.SUPPLIERS(SUPPLIER_ID) NOCHECK;  
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_B2 FOREIGN KEY(SUPPLIER_ID) REFERENCES PUBLIC.SUPPLIERS(SUPPLIER_ID) NOCHECK;            
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT_HISTORY ADD CONSTRAINT PUBLIC.CONSTRAINT_FFF FOREIGN KEY(SUPPLIER_PAYMENT_ID) REFERENCES PUBLIC.SUPPLIER_PAYMENT(SUPPLIER_PAYMENT_ID) NOCHECK;            
ALTER TABLE PUBLIC.SUPPLIER_PAYMENT_ITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_78 FOREIGN KEY(SUPPLIER_PAYMENT_ID) REFERENCES PUBLIC.SUPPLIER_PAYMENT(SUPPLIER_PAYMENT_ID) NOCHECK;
ALTER TABLE PUBLIC.PAYMENT_ITEAM ADD CONSTRAINT PUBLIC.CONSTRAINT_598 FOREIGN KEY(PAYMENT_ID) REFERENCES PUBLIC.PAYMENT(PAYMENT_ID) NOCHECK;  
ALTER TABLE PUBLIC.PAYMENT_HISTORY ADD CONSTRAINT PUBLIC.CONSTRAINT_C FOREIGN KEY(CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMER(CUSTOMER_ID) NOCHECK;               
